### ISSUE TITLE
Package couldn't be installed(irrelevant errors) need latest version of Vs

### ISSUE THREAD

**Issue by Youssuf-bakry** [cajmorgan/float-to-fraction#1]
Hi all 
I get a bunch of errors while trying to install this package using `npm install float-to-fraction`

some of these errors are (however I 've the latest version of VS code)

svs_version was set from command line or npm config
npm ERR! gyp ERR! find VS - looking for Visual Studio version 2017
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS checking VS2019 (16.11.31911.196) found at:
npm ERR! gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
npm ERR! gyp ERR! find VS - found VC++ toolset: v142
npm ERR! gyp ERR! find VS - missing any Windows SDK
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS valid versions for msvs_version:
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows

I'm completely new to programming and I hope you guide me 
REGARDS,

**Comment by cajmorgan** [comment]
Hey!

I’d suggest to not use this library, I wrote it a while back to test some C bindings to Node. 

I think it might not work on certain computer architectures! 

Just a tip, be aware what libraries you download through NPM, there is a lot of bad stuff (like this one) ;)
